-- Cleanup
use master
go
-- Disabling the Classifier 
ALTER RESOURCE GOVERNOR WITH (CLASSIFIER_FUNCTION = NULL)
GO
-- make the changes effective
ALTER RESOURCE GOVERNOR RECONFIGURE
GO
DROP FUNCTION CLASSIFIER_V1
GO

---- DROP ALL THE FUNCTIONALITY 
DROP WORKLOAD GROUP Group_Operations
DROP WORKLOAD GROUP Group_Sales
DROP WORKLOAD GROUP Group_MKT

DROP RESOURCE POOL Pool_Operations
DROP RESOURCE POOL Pool_SalesMKT

USE AdventureWorks2022
GO
DROP USER UserOperations
DROP USER UserSales
DROP USER UserMarketing

USE Master
GO
DROP LOGIN UserOperations
DROP LOGIN UserSales
DROP LOGIN UserMarketing
GO

ALTER RESOURCE GOVERNOR DISABLE;
GO
