ALTER DATABASE AdventureWorks2022 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE AdventureWorks2022 SET READ_COMMITTED_SNAPSHOT OFF;
GO

ALTER DATABASE AdventureWorks2022 SET MULTI_USER;
GO

SELECT is_read_committed_snapshot_on FROM sys.databases 
WHERE name= 'AdventureWorks2022'


