CREATE EVENT SESSION [BlockedProcessReport] ON SERVER 
ADD EVENT sqlserver.blocked_process_report
ADD TARGET package0.ring_buffer(SET max_events_limit=(0),max_memory=(2048))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO

ALTER EVENT SESSION [BlockedProcessReport]
ON SERVER
STATE=START
GO

